markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: vvzvlad
author: "vvzvlad"
email: vvzvlad@gmail.com
name: "vvzvlad"
baseurl: /
url: http://vvzvlad.xyz
domain: vvzvlad.xyz

all_categories: [
  ["android", "Android","/android/index.html"], 
  ["react", "React Native", "/react/index.html"],
  ["web", "Web","/web/index.html"], 
  ["linux", "linux","/linux/index.html"],
  ["git", "git","/git/index.html"],
  ["program", "program","/program/index.html"],
  ["vps", "VPS","/vps/index.html"],
  ["other", "other","/other/index.html"],
  ["read", "read","/read/index.html"], 
  ["about", "about","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
